version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  # Maintain dependencies for NodeJS
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - nodejs

  # Maintain dependencies for Python
  - package-ecosystem: python
    directory: hello-cdk/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
