version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "monday"
    labels:
      - dependencies
      - github-actions

  # Maintain dependencies for Node.js
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: "monday"
    labels:
      - dependencies
      - nodejs

  # Maintain dependencies for Python
  - package-ecosystem: pip
    directories:
      - hello-cdk
      - hello-cdk/hello_cdk/lambda_src
    schedule:
      interval: weekly
      day: "monday"
    groups:
      prod-deps:
        dependency-type: "production"
        patterns:
          - aws-cdk-lib
          - aws-cdk.cloud-assembly-schema
          - constructs
          - jsii
          - ruamel.yaml
      dev-deps:
        dependency-type: "development"
        patterns:
          - pytest
          - pylint
    allow:
      - dependency-type: "all"  # includes dev deps too
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
