block-list-secret-scan: []
framework:
  - cloudformation
  # - cdk # Paid feature
mask: []
output:
  - cli
  - sarif
  - github_failed_only
secrets-scan-file-type: []
summary-position: top
quiet: true
soft-fail: true
compact: true
skip-path: []
skip-check:
  - CKV_AWS_115 # For testing purposes not set
  - CKV_AWS_116 # AWS Lambda function doesn't require a Dead Letter Queue(DLQ)
  - CKV_AWS_117 # For testing purposes no need for lambda to be in VPC
  - CKV_AWS_119 # For testing purposes use AWS Managed KMS for DynamoDB encryption
  - CKV_AWS_158 # For testing purposes, using default AWS Managed KMS for CloudWatch Log Group encryption
  - CKV_AWS_173 # For testing purposed use default for Lambda environment encryption
  - CKV_AWS_258 # For testing purposes Lambda function URLs AuthType is set to None
