name: Determine prefix
description: Reusable action for determining the prefix for CDK stack from Git branch

inputs:
  branch_name:
    description: The name of the branch to determine prefix for
    required: true
    default: ${{ github.ref }}

outputs:
  prefix:
    description: The determined CDK stack prefix based on the branch
    value: ${{ steps.get_prefix.outputs.prefix }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/determinePrefix.sh "$BRANCH_NAME"
      id: get_prefix
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.branch_name }}
