# Clean up resources after PR is merged
name: CI cleanup

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  python_version: 3.13
  working_directory: hello-cdk

permissions:
  contents: read
  id-token: write

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged == true
    environment: dev-branch
    env:
      AWS_REGION:: ${{ vars.AWS_REGION }}
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Determine Stack prefix
        id: stack_prefix
        uses: ./.github/actions/get-prefix
        with:
          branch_name: ${{ github.event.pull_request.head.ref }}

      - name: Setup tooling
        uses: ./.github/actions/setup
        with:
          python_version: ${{ env.python_version }}
          working_directory: ${{ env.working_directory }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_OIDC_ROLE }}
          role-session-name: AssumeGitHubOIDCRole

      - name: List CDK Stacks
        run: |
          echo "### CDK list" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npx cdk list --context stack_prefix=${{ steps.stack_prefix.outputs.prefix }} --ci --show-dependencies | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Run CDK Destroy
        run: |
          echo "### CDK destroy" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npx cdk destroy --context stack_prefix=${{ steps.stack_prefix.outputs.prefix }} --ci --all --force 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> $GITHUB_STEP_SUMMARY
