name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  python_version: 3.13

concurrency:
  group: ci-${{ github.head_ref || github.ref_name }}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      AWS_REGION:: ${{ vars.AWS_REGION }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python_version }}
          cache: 'pip'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hello-cdk/requirements.txt

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
           node-version-file: '.nvmrc'
           cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Print CDK version
        run: npx aws-cdk --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_OIDC_ROLE }}
          role-session-name: AssumeGitHubOIDCRole

      - name: Check AWS authentication
        run: aws sts get-caller-identity
