name: CI pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

env:
  python_version: 3.13
  git_chglog_version: 0.15.4
  working_directory: hello-cdk
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

concurrency:
  group: ci-${{ github.head_ref || github.ref_name }}

permissions: read-all

jobs:
  determine-version:
    uses: ./.github/workflows/determine-version.yml

  build:
    needs: [determine-version]
    runs-on: ubuntu-24.04
    outputs:
      stack_prefix: ${{ steps.stack_prefix.outputs.prefix }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Determine Stack prefix
        id: stack_prefix
        uses: ./.github/actions/get-prefix
        with:
          branch_name: ${{ env.BRANCH_NAME }}

      - name: Output the stack prefix
        run: |
          echo "The CDK branch stack prefix is ${{ steps.stack_prefix.outputs.prefix }}"
          echo "::notice title=CDK Stack prefix::CDK Stack prefix is ${{ steps.stack_prefix.outputs.prefix }}"

      - name: Build and run tests
        run: echo "Do some build and tests here. TODO"

  cdk-diff:
    needs: [build]
    if: >-
      ${{
        (contains(github.event.pull_request.labels.*.name, 'deploy-infra') && github.ref_name != 'main') ||
         github.ref_name == 'main'
      }}
    runs-on: ubuntu-24.04
    environment: dev-branch
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    env:
      AWS_REGION:: ${{ vars.AWS_REGION }}
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    outputs:
      has_changes: ${{ steps.diff.outputs.has_changes }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup tooling
        uses: ./.github/actions/setup
        with:
          python_version: ${{ env.python_version }}
          working_directory: ${{ env.working_directory }}
          aws_region: ${{ vars.AWS_REGION }}
          role_to_assume: ${{ vars.AWS_OIDC_ROLE }}

      - name: Synth CDK stacks
        run: npx cdk synth --context stack_prefix=${{ needs.build.outputs.stack_prefix }} --ci

      - name: Plan CDK Deploy to AWS
        id: diff
        run: |
          set +e
          npx cdk diff --context stack_prefix=${{ needs.build.outputs.stack_prefix }} --ci --all --fail --quiet | tee cdk.diff
          RC=${PIPESTATUS[0]}
          echo "cdk diff exit code: $RC"

          if [[ $RC -eq 0 ]]; then
            echo "No changes found"
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            exit 0
          elif [[ $RC -eq 1 ]]; then
            # 1 usually means "diff found", but can be other errors.
            if grep -E "Number of stacks with differences:|^\s*\[\+|\[\~|\[\-\]" cdk.diff >/dev/null; then
              echo "has_changes=true" >> "$GITHUB_OUTPUT"
              exit 0
            else
              echo "Unexpected CDK error:"
              cat cdk.diff
              exit 2
            fi
          else
            # Any other non-zero is a real error
            exit $RC
          fi

      - name: Update Summary
        id: diff_summary
        run: |
          echo "### CDK diff" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat cdk.diff >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Post CDK diff output in PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Read diff file contents
            const fs = require('fs');
            process.chdir(process.env.working_directory);
            const content = fs.readFileSync('cdk.diff', { encoding: 'utf8', flag: 'r' });

            // Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Find and delete all previous bot comments so PR timeline is kept clean
            for (const comment of comments) {
              if (comment.user.type === 'Bot' && comment.body.includes('CDK diff')) {
                await github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id,
                });
              }
            }

            const output = `#### CDK diff 📖\`${{ steps.diff_summary.outcome }}\`

            <details><summary>Show CDK diff for Deployment: </summary>

            \`\`\`\n
            ${content}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  cdk-drift:
    needs: [build, cdk-diff]
    runs-on: ubuntu-24.04
    environment: dev-branch
    permissions:
      contents: read
      id-token: write
    env:
      AWS_REGION:: ${{ vars.AWS_REGION }}
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup tooling
        uses: ./.github/actions/setup
        with:
          python_version: ${{ env.python_version }}
          working_directory: ${{ env.working_directory }}
          aws_region: ${{ vars.AWS_REGION }}
          role_to_assume: ${{ vars.AWS_OIDC_ROLE }}

      - name: Run CDK Drift Detection
        run: |
          set -euo pipefail

          # Get all stacks (remove empty lines)
          mapfile -t STACKS < <(
            npx cdk list --context stack_prefix=${{ needs.build.outputs.stack_prefix }} --ci | awk 'NF'
          )

          if [ "${#STACKS[@]}" -eq 0 ]; then
            echo "No stacks found via 'cdk ls'."
            exit 0
          fi

          echo "Found ${#STACKS[@]} stack(s):"
          for s in "${STACKS[@]}"; do echo "$s"; done

          DRIFTED=0

          echo "### CDK drift" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          for stack in "${STACKS[@]}"; do
            set +e
            npx cdk drift --context stack_prefix=${{ needs.build.outputs.stack_prefix }} "$stack" --ci --fail | tee -a "$GITHUB_STEP_SUMMARY"
            RC=$?
            set -e
            if [[ $RC -eq 1 ]]; then
              DRIFTED=$((DRIFTED+1))
            elif [[ $RC -ne 0 ]]; then
              echo "Error checking drift for stack $stack, cdk drift exit code: $RC"
              exit $RC
            fi
          done
          echo "Total drifted stacks found: $DRIFTED" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          # Print warning message if any drifted stacks found
          if [[ $DRIFTED -gt 0 ]]; then
            echo "::warning ::DRIFTED stacks found: $DRIFTED"
          fi

  cdk-deploy:
    needs: [build, cdk-diff, cdk-drift]
    if: ${{ needs.cdk-diff.outputs.has_changes == 'true' }}
    runs-on: ubuntu-24.04
    environment: ${{ github.ref == 'refs/heads/main' && 'dev' || 'dev-branch' }}
    permissions:
      contents: read
      id-token: write
    env:
      AWS_REGION:: ${{ vars.AWS_REGION }}
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup tooling
        uses: ./.github/actions/setup
        with:
          python_version: ${{ env.python_version }}
          working_directory: ${{ env.working_directory }}
          aws_region: ${{ vars.AWS_REGION }}
          role_to_assume: ${{ vars.AWS_OIDC_ROLE }}

      - name: Run CDK Deploy
        run: |
          echo "### CDK deploy" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npx cdk deploy --context stack_prefix=${{ needs.build.outputs.stack_prefix }} --ci --all --require-approval=never | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> $GITHUB_STEP_SUMMARY

  run-tests:
    needs: [build, cdk-diff, cdk-deploy]
    if: ${{ !cancelled() && needs.cdk-diff.result == 'success' }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Run some tests
        run: echo "Run some E2E tests against deployed resources. TODO"

  release:
    needs: [determine-version, run-tests]
    if: ${{ always() && github.ref_name == 'main' && needs.run-tests.result == 'success' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch full history to include tags

      - name: Get new tag
        run: echo "NEW_TAG=${{ needs.determine-version.outputs.next_version }}" >> $GITHUB_ENV

      - name: Set up git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push Release Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag "$NEW_TAG"
          git push origin tag "$NEW_TAG"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --current
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$NEW_TAG" \
            --title="Release $NEW_TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --notes-file=CHANGELOG.md \
            --latest \
            --verify-tag
