# Publish Deployment logs to GH Pages

on:
  workflow_call:
    inputs:
      version:
        description: The version being deployed
        required: true
        type: string
      environment:
        description: The deployment environment
        required: true
        type: string

permissions:
  contents: write

concurrency:
  group: gh-pages
  cancel-in-progress: false

jobs:
  publish-to-github-pages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: gh-pages     # GH Pages branch
          persist-credentials: true
          fetch-depth: 1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
